ALTER TABLE PortDef ADD RequestStatus int;
ALTER TABLE PortDef ADD ErrorFlag bit;
ALTER TABLE PortDef ADD IgnoreStatusFlag bit DEFAULT 0 NOT NULL;
ALTER TABLE APORTSTATION ADD IGNORE_STATUS_FLAG bit DEFAULT 0 NOT NULL;